name: Load Verdaccio with Code Snippets
description: Turn on Verdaccio and load up Code Snippets

runs:
  using: 'composite'
  steps:
    - name: Start verdaccio
      run: |
        npx verdaccio@5.25.0 &
        while ! nc -z localhost 4873; do
          echo "Verdaccio not running yet"
          sleep 1
        done

        # Run your commands after verdaccio is up and running
        echo "Verdaccio is up and running, proceeding with the script..."
      shell: bash

    - name: Install and run npm-cli-login
      shell: bash
      env:
        NPM_REGISTRY: http://localhost:4873/
        NPM_USER: verdaccio
        NPM_PASS: verdaccio
        NPM_EMAIL: verdaccio@amplify.js
      run: |
        npm i -g npm-cli-adduser
        npm-cli-adduser --username $NPM_USER --password $NPM_PASS --email $NPM_EMAIL
        sleep 1

    - name: Configure registry and git
      shell: bash
      working-directory: ./docs
      env:
        NPM_REGISTRY: http://localhost:4873/
        NPM_USER: verdaccio
        NPM_PASS: verdaccio
        NPM_EMAIL: verdaccio@amplify.docs
      run: |
        yarn config set registry $NPM_REGISTRY
        npm set registry $NPM_REGISTRY
        git config --global user.email $NPM_EMAIL
        git config --global user.name $NPM_USER
        git status
        git --no-pager diff

    - name: Publish to verdaccio
      shell: bash
      working-directory: ./docs/codenippets
      run: |
        npm publish
