name: Run E2E Tests

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [e2e-test-trigger]
  schedule:
    - cron: '0 0 */2 * *' # Every 2 days

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v2

      - name: Checkout Example App from Repo B
        uses: actions/checkout@v2
        with:
          repository: Aadim1/amplify-js-samples-staging
          path: samples-staging
          token: ${{ secrets.GH_TOKEN_STAGING_READ_AADIM }}

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Set up code snippets
        run: |
          mkdir -p ./samples-staging/samples/docs/example-docs-app/src/codesnippets
          cp -r ./codesnippets/* ./samples-staging/samples/docs/example-docs-app/src/codesnippets

      - name: Install Dependencies
        run: npm install
        working-directory: ./samples-staging/samples/docs/example-docs-app
      
      - name: Run Sample App
        run: npm run dev

      - name: Run E2E Tests
        run: npm run ci:docs
        working-directory: ./samples-staging

      # Note implemented yet.
      # - name: Send Alert on Failure
